export const USER_PROFILE_DETAILS_REQUEST = "USER.PROFILE_DETAILS_REQUEST";
export const USER_PROFILE_DETAILS_SUCCESS = "USER.PROFILE_DETAILS_SUCCESS";
export const USER_PROFILE_DETAILS_FAIL = "USER.PROFILE_DETAILS_FAIL";
export const USER_PROFILE_DETAILS_RESET = "USER.PROFILE_DETAILS_RESET";
